### ISSUE TITLE
Issues when using artifact-deploy from an S3 source on a Windows Client

### ISSUE THREAD

**Issue by dparkar** [RiotGamesCookbooks/artifact-cookbook#100]
1) credentials data-bags : I couldn't get it to use custom naming for data-bags, I had to use a data-bag called "aws" with item name "_wildcard". I am not sure if it was intentional, if so then I would suggest documenting a little more explicitly instead of giving it as an example.

2) I could get the file downloaded but wasn't able to unzip in the right directory, I thought this fix for Windows cookbook could help : https://github.com/torresdal/windows/commit/453ef82d516975c3baca898949d958ef17230042 
But I am not sure if that helped because of (3)

3) Even though I used (2), unzip failed with a different error and I couldn't even manually unzip the file downloaded from s3. A little google and realized that when file is being downloaded and written to disk the "w" flag is used, when I changed it to "wb" finally I got everything to work i.e. download from s3 with the credentials and unzip the contents in a desired folder. A similar issue can be found here : http://stackoverflow.com/questions/12352230/using-aws-sdk-to-download-files-from-s3-encoding-not-right
The part of code I am talking about is on Line 152 of libraries/chef_artifact.rb file

**Comment by KAllan357** [comment]
@LawfulEvil Thanks for the report.

1) I think data bags in general might need an overhaul. I think any large changes in data bags would result in a 2.0.0 release, and we'd need to come up with a good way to simplify things. For now, maybe some better documentation would help.

2) Hopefully there will be a new cut of the Windows cookbook soon to fix this issue. In the meantime, I've worked around it by adding an attribute that the Windows cookbook honors - `default['windows']['rubyzipversion'] = "0.9.9"`. This solution is slightly less intrusive than pulling that branch and switching it in your Berksfile.

3) I will open a separate issue and perhaps @jonathanq can weigh in.

**Comment by dparkar** [comment]
Thanks KAllan357 !

**Comment by jonathanq** [comment]
I was on vacation - so just catching up on this now.  @KAllan357 @LawfulEvil - Does the switch to binary mode fix the issue on Windows?  Or is there still something I can look into to resolve this?

**Comment by dparkar** [comment]
"wb" definitely worked for Windows. Don't think anything else is required from the POV of downloading from S3 and unzipping in a particular location.
