### ISSUE TITLE
Duplicate extract directory

### ISSUE THREAD

**Issue by geerzo** [RiotGamesCookbooks/artifact-cookbook#102]
I'm using the remove_top_level_directory attribute set to true to unpack the archive directly into the `releases/<version>` directory. This works great but on some subsequent runs I wind up with the archive unpacked again into the `releases/<version>/<artifact>` directory.

**Comment by andrewGarson** [comment]
@geerzo Is this when you upgrade a package to a new version or just when you run chef again w/o changing versions?

**Comment by geerzo** [comment]
It's when running again without changing the version.

Sent from my iPhone

On Oct 3, 2013, at 5:46 PM, Andrew Garson notifications@github.com wrote:

@geerzo https://github.com/geerzo Is this when you upgrade a package to a
new version or just when you run chef again w/o changing versions?

—
Reply to this email directly or view it on
GitHubhttps://github.com/RiotGames/artifact-cookbook/issues/102#issuecomment-25661063
.

**Comment by andrewGarson** [comment]
It shouldn't be trying to redeploy at all in that case. Is there any chance you could provide a repro case so I can try it here?

**Comment by geerzo** [comment]
It was redeploying because a config file had changed which caused the manifest to vary. I will see if I can put together an example at some point.
