### ISSUE TITLE
artifact_file 'path' argument is not functionnal

### ISSUE THREAD

**Issue by BarthV** [RiotGamesCookbooks/artifact-cookbook#122]
Hi !
This is working :

```
artifact_file '/tmp/test-1.3.175.jar' do
  location 'com.test:test:jar:1.3.175'
  nexus_configuration nexus_conn
  owner 'root'
  group 'root'
end
```

This is not :

```
artifact_file 'test jar' do
  path '/tmp/test-1.3.175.jar'
  location 'com.test:test:jar:1.3.175'
  nexus_configuration nexus_conn
  owner 'root'
  group 'root'
end
```

`artifact_file` LWRP seems to totally ignore path option (`path` doesn't seems to be mentionned once in the provider code).
Tell me if you want me to dive a bit into file.rb provider file, and sumbit a fix.

**Comment by KAllan357** [comment]
I think originally this was written with the name attribute being the important attribute. I am okay with adding in a path attribute, I will take a look at the pull.

**Comment by BarthV** [comment]
According to resource file and cookbook readme, path attr is already present and available.
It's not really an addition for me .. Only a very simple fix :)

**Comment by BarthV** [comment]
closing this one, some merged PR fixed this.
