### ISSUE TITLE
Speed up LWRP run

### ISSUE THREAD

**Issue by BarthV** [RiotGamesCookbooks/artifact-cookbook#130]
Hi,

Currently each time you call one of the artifact's LWRP, it loads a bunch of deps and gems.

For one of my project, I'm working with a large number of artifacts and Chef takes a very long time (10~20 min) only to install/update chef_gem for each lwrp.

Maybe it would be interesting to provides a single recipe which would load all needed gems and dependencies, and then makes repetitives call lighter and faster ?

**Comment by KAllan357** [comment]
Hi @BarthV,

Can you give a bit more detail? The requires for the nexus-cli and aws gem's _should_ not be loaded unless they are needed. It would be interesting to see some metrics of where the time is being spent.

**Comment by BarthV** [comment]
I'll build a test server with a powerful hardware/network tomorrow and write down some metrics from our live Nexus.

For now, I'm really convinced that each time you call a lwrp, it fires a chef_gem action who is checking rubygem repositories and trying to update the gems everytime (this takes a while each time) .. I was just thinking a way to refactor all these redundant calls to only trigger once in a run.

More contents following soon

**Comment by BarthV** [comment]
After testing deploying 20 different Nexus artifact in a test recipe, I see that chef_gem takes ages only in my vagrant VMs (I don't have a rly bad hardware I think): 
20~30 sec for each `chef_gem[nexus_cli] action install` call
On a server grade hardware chef_gem call is nearly seamless, so it's fine.

30sec run to re-converge the same recipe versus 3m40 on my Vagrant :-/

I close this, ty

**Comment by KAllan357** [comment]
Ah this makes more sense now. I am forgetting the exact fix, but I believe I've noticed this when Vagrant is running on either a public or private network. In fact, I might have added the answer to this stackoverflow to my Vagrantfile in some cases - http://serverfault.com/questions/495914/vagrant-slow-internet-connection-in-guest
