### ISSUE TITLE
use_symlinks option to deploy without symlinks

### ISSUE THREAD

**Issue by florentdupont** [RiotGamesCookbooks/artifact-cookbook#147]
I'd like to propose a feature that could allow a **deployment without the use of symlinks**.

This feature could be available through a new parameter called `use_symlinks` (default to `true`).
The behavior of any artifact deployment stays the same if the option is not set or set to `true` (default value).

If `use_symlinks` is `false` then no symlinks are used for the deployment but are still following the releases/current/shared convention, which means : 
- current is a regular directory
- files are copied as usual in the `releases` directory.
- the current version (= the last deployed artifact in `releases`) is also copied in the `current` directory
- a new file `version.txt` (available at the root = same level as `releases`/`current`/`shared`) contains the version which is actually contained in `current`. This file is used for further artifact deployment to know if the deployment should be done or not.

Here's a schema explaining the differences between the two options :

![symlinks_differences](https://cloud.githubusercontent.com/assets/1887329/3923368/c65635a4-23d2-11e4-8d0b-53f2a969804d.png)

This feature is actually developed (and used) internally with an older version of the artifact-cookbook (1.3.1). We are planning to merge this modification soon to version 1.12.1 (still internally). We'd like to pull-request this feature to help people to use older OSes that don't support symlinks (Windows 2003 for instance) to perform an artifact deployment this way.

Do you think we could perform a pull-request and if it's gonna be accepted ? 
Any question, improvement is welcomed.

**Comment by KAllan357** [comment]
:+1: - I think this is a great idea. For Riot we've only needed to support Unix and Windows 2008R2 - both of which support symlinks (or junctions). 

I'm all for supporting other OSes with the optional attribute you describe.

**Comment by florentdupont** [comment]
merged in PR #150
