### ISSUE TITLE
Avoid the package extraction

### ISSUE THREAD

**Issue by ntorres-globant** [RiotGamesCookbooks/artifact-cookbook#163]
My application doesn't need to extract the war package. In fact "unzip" is not installed.
Is it possible to skip the package extraction with a flag or something like it?

Thanks!

**Comment by BarthV** [comment]
I did it on my own wrapper. I'll check the code later, but it's not impossible at all :)

**Comment by ntorres-globant** [comment]
Actually, the version here: https://supermarket.chef.io/cookbooks/artifact/versions/1.12.1 (that is what the chef server automatically downloads when requested) is different from this repository contents.

The supermarket version has the package extraction for war files and the github version does not.

Since I need the later behaviour I just downloaded the code and manually uploaded to the chef server bypassing the supermarket.

Thanks BarthV for your response.

More details

Here: https://github.com/RiotGamesCookbooks/artifact-cookbook/blob/master/providers/deploy.rb

```
when /(war|jar)$/
  ruby_block "Copy War/JAR File to Release_Path" do
    block do
      ::FileUtils.cp "#{cached_tar_path}", "#{release_path}"
    end
```

and the supermarket version (BTW: both same version number 1.12.1)

  when /zip|war|jar/
      if Chef::Artifact.windows?
        windows_zipfile release_path do
          source    cached_tar_path
          overwrite true
          retries 2
        end
      else
        package "unzip"
        execute "extract_artifact!" do
          command "unzip -q -u -o #{cached_tar_path} -d #{release_path}"
          user    new_resource.owner
          group   new_resource.group
          retries 2
        end
      end

**Comment by frntn** [comment]
I'm having the same issue here.
Any idea when the supermarket repo will be synced ? (I 'd like to keep on using Berkshelf and prevent myself from manual hacks)
