### ISSUE TITLE
Rollback

### ISSUE THREAD

**Issue by kief** [RiotGamesCookbooks/artifact-cookbook#23]
Hi,

Handy cookbook, I much prefer the model of using an artifact in a repo to pulling from source control.

As far as I can see, there's no way to roll back to a previous release. If I run with version set to 1.0, then again set to 2.0, then a third time setting the version to 1.0, then version 2.0 is still in place. 

I'd expect it to relink to the 1.0 release and restart the app, but instead it seems to consider it as already deployed, and skips (unless force is set to true, of course).

I can hack around it for myself, but would be handy if it did the rollback to a previous version.

Thanks,
Kief

**Comment by ivey** [comment]
Are you sure you have the latest version? I believe this was (supposed to be) fixed in a849beba8cd58fc38f8d2a7b06ce3ff28d39e15a

**Comment by KAllan357** [comment]
@ivey, I don't think a849beba8cd58fc38f8d2a7b06ce3ff28d39e15a was meant to fix the bug described here. In the current version of the code (and possibly previous versions as well) when you attempt to "roll back" to an already released version, the `deployed?` check will return true and the resource won't do anything - including switch the `current` symlink to the 'new' version.

**Comment by ivey** [comment]
`if get_previous_release_version != new_resource.version`

Seems like it will do a deploy regardless of what version is deployed, if it's not the one we're trying to deploy, right?

I'm working on a test harness for this cookbook, so I can confirm shortly.

**Comment by KAllan357** [comment]
@kief I believe this should be fixed in the 1.0.0 release.

Please change your dependency to the new release and let me know if you experience this bug again.

Kyle
