### ISSUE TITLE
Name of resource could break deployment

### ISSUE THREAD

**Issue by choubacha** [RiotGamesCookbooks/artifact-cookbook#35]
The name of the resource is used in the artifact path but white-space is not removed. If the name contains spaces, for example, the shell commands will most likely fail or behave unpredictably

``` ruby
@artifact_root          = ::File.join(@new_resource.artifact_deploy_path, @new_resource.name)

...

def extract_artifact
  execute "extract_artifact" do
    command "tar xzf #{cached_tar_path} -C #{release_path}"
    user new_resource.owner
    group new_resource.group
  end
end

def copy_artifact
  execute "copy artifact" do
    command "cp #{cached_tar_path} #{release_path}"
    user new_resource.owner
    group new_resource.group
  end
end
```

In the above code, if the name was "Deploying Files for User" then the `command` being sent to the execute resource would be:

"cp /tmp/artifacts/Deploying Files for User /home/user"

The spaces will break the shell script and the chef-client will fatally error.

We might try to do a gsub on the name when putting it into artifact_root. Something like:

``` ruby
@artifact_root          = ::File.join(@new_resource.artifact_deploy_path, @new_resource.name.gsub(/\W/, '_'))
```

**Comment by ivey** [comment]
Like other resources where the name is significant, the name should be the name of the artifact. I'd be more inclined to support throwing an error on whitespace, or some proper escaping on the shell commands.
