### ISSUE TITLE
Restart proc does not run when symlink is changing but artifact remains unchanged

### ISSUE THREAD

**Issue by rkialashaki** [RiotGamesCookbooks/artifact-cookbook#59]
For testing purposes, it is nice to see what sequential chef runs will do when deploying the same artifact but incrementing the version number in the artifact_deploy resource.  When doing so, the restart proc does not run.  It seems that the restart proc will only run when the manifest is changed and not when only a symlink is changing.

**Comment by KAllan357** [comment]
The logic in the provider for running the restart proc is as follows:

```
if deploy? || manifest_differences? || current_symlink_changing?
    run_proc :restart
end
```

This sounds like a bug, possibly one in the `current_symlink_changing?` method. Just to be clear, what you are doing is:
1. Installing some artifact; restart proc runs.
2. Installing another artifact; restart proc runs.
3. Switching back to the old one; restart proc doesnt run.

Is that the behavior you are seeing?

**Comment by rkialashaki** [comment]
The behavior is this:

1.) in the cookbook, using artifact_deploy to deploy version 1.0 of an artifact for example:

artifact_deploy "artifact" do
  version "1.0"
  artifact_location "http://artifacts.server.com/artifact-1.0.tar.gz"

2.) restart proc runs on the first chef run

3.) increment the version in the cookbook but not on the artifact location:

artifact_deploy "artifact" do
  version "1.1"
  artifact_location "http://artifacts.server.com/artifact-1.0.tar.gz"

4.) restart proc does not run even thought the symlink is changing from releases/1.0 to releases/1.1

**Comment by KAllan357** [comment]
After working with @rkialashaki and his cookbook, we came to the conclusion that the problem was related to the `runit_service` definition and the recipe in general. Closing this issue.
