### ISSUE TITLE
Verify checksum

### ISSUE THREAD

**Issue by ivey** [RiotGamesCookbooks/artifact-cookbook#61]
If an attr with the artifact.s checksum s included, verify successful download before continuing

**Comment by KAllan357** [comment]
Does the `artifact_checksum` work for you? I believe it should be used and checked when the `retrieve_artifact!` method is executed.

https://github.com/RiotGames/artifact-cookbook/blob/master/providers/deploy.rb#L541-L564

**Comment by ivey** [comment]
Cool. Rob Smith and I were talking and I didn't realize it did this. I'll let him know!
