### ISSUE TITLE
Unable to specify multiple nexus repositories

### ISSUE THREAD

**Issue by tberman** [RiotGamesCookbooks/artifact-cookbook#78]
Doesn't seem like there is a way to do it currently.

**Comment by KAllan357** [comment]
Thats a good point. Do you think you would find a `repository` attribute useful on the resource? That way you could use an attribute to help further define where the artifact comes from.

**Comment by tberman** [comment]
Only issue with that is username/password combinations as well, probably don't want them in plain text in the resource

**Comment by andrewGarson** [comment]
@tberman you should store those in encrypted data bags, then pull them out via a library and pass that to the resource. That could even be baked into the deploy resource....define a repositories hash and the resource just gives the key
