### ISSUE TITLE
ssl_verify false no longer works in 1.6.0 and above.

### ISSUE THREAD

**Issue by ckw4y** [RiotGamesCookbooks/artifact-cookbook#82]
checksum_valid calls Chef::Artifact.get_artifact_sha without passing in the ssl_verify flag

**Comment by ivey** [comment]
Can I see the resource you're using when you see this problem?

**Comment by ckw4y** [comment]
It happens on any artifact_deploy resource that has artifact_location set to a maven identifier when the nexus server doesn't have a valid ssl certificate.

The actual bug is on providers/file.rb:70. Chef::Artifact.get_artifact_sha needs the 3rd parameter to be new_resource.ssl_verify

**Comment by capoferro** [comment]
#85 may fix part or all of this issue due to my needing to float ssl_verify through the artifact_file resource. Should confirm.
