### ISSUE TITLE
Anonymous access doesn't seem to work for me

### ISSUE THREAD

**Issue by gregsymons** [RiotGamesCookbooks/artifact-cookbook#88]
I see that you recently accepted a pull that makes the cookbook work if anonymous access is disabled, however, I can't figure out how you used anonymous access in the first place. If I omit the `username` and `password` fields from the data bag or set them to blank, then `nexus_cli` complains about them being missing. If I set them to `"anonymous"` then `anonymous_enabled?` fails because the anonymous user doesn't have the privileges to check to see if it's enabled. Does anonymous access actually work?

**Comment by gregsymons** [comment]
Oh, and if I set the `username` and `password` fields for a different user that doesn't have the permissions to get user information, I get the same error as if I tried to use anonymous.

**Comment by KAllan357** [comment]
@gregsymons Thank you for pointing this out - I also noticed this problem yesterday. @bluepojo and myself have been working on addressing these shortcomings in both an update to this cookbook and some necessary changes to the nexus-cli gem.

If you are interested in trying out some of these changes locally and verifying our work, you can use the branch from this pull request - https://github.com/RiotGames/artifact-cookbook/pull/89 (if you are using Berkshelf and Vagrant).

In any case, we hope to have a fix for this problem completed shortly.

**Comment by gregsymons** [comment]
I'll keep an eye on it... When you bring in the new nexus_cli with anonymous support, I'll see if I can test it on my cookbook. I assume I have to wait for that for anonymous access to actually work, right?

**Comment by KAllan357** [comment]
Yes, that is true. Very sorry for the inconvenience.

**Comment by gregsymons** [comment]
Not a problem... My cookbook isn't ready for production yet, anyway.

**Comment by KAllan357** [comment]
@gregsymons Could you give 1.10.0 or higher and try this out again?

**Comment by gregsymons** [comment]
It looks like 1.10 solves my problem.
